# This is a basic workflow to help you get started with Actions

name: hello-worldWF

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: my-step1.1
        run: echo Hello, world!
      - name: my-step1.2
        run: sleep 20
      - name: my-step1.3
        run: echo Welcome!
  job2:
 
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:

      # Runs a single command using the runners shell
      - name: my-step2.1
        run: echo Hello, world!
      - name: my-step2.2
        run: sleep 20
      - name: my-step2.3
        run: echo Welcome!
